version: '3.8'
services:
  app:
    build: .
    restart: always
    volumes:
      - .:/django
    ports:
      - 8000:8000
    image: app:django
    container_name: django_container
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    networks:
      - mynetwork

  db:
    image: postgres:latest
    restart: always
    # volumes:
    #   - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: postgres_db
    networks:
      - mynetwork

networks:
  mynetwork:
