apiVersion: v1
kind: ConfigMap
metadata:
  name: app-variables
data:
  #env variables for the postgres component
  POSTGRES_USER: postgres
  POSTGRES_DB: app
  #env variables for the backend component
  DJANGO_ALLOWED_HOSTS: "*"
  DATABASES: postgres
  DB_ENGINE: "django.db.backends.postgresql"
  DB_NAME: app
  DB_USER: postgres
  DB_HOST: postgres-cluster-ip-service
  DB_PORT: "5432"