version: '3.8'
services:
  app:
    build: .
    restart: always
    volumes:
      - .:/django
    ports:
      - 8000:8000
    image: app:django
    container_name: django_container
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
    networks:
      - mynetwork
    env_file:
      - .env  

  db:
    image: postgres:15.5-bullseye
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql
    container_name: postgres_db
    networks:
      - mynetwork
    env_file:
      - .env  

networks:
  mynetwork: