apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{.Release.Name}}-django-deployment"
  labels:
    app: {{.Values.labelsAppDjango}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.Values.labelsAppDjango}}
  template:
    metadata:
      labels:
        app: {{.Values.labelsAppDjango}}
    spec:
      containers:
      - name: django-container
        image: rodricamio/crud-django-postgres:6
        command: ["python","./manage.py", "runserver", "0.0.0.0:8010"]
        ports:
        - containerPort: {{.Values.ContainerPortDjango}}
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: "{{ .Release.Name }}-postgres-credentials"
              key: user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: "{{ .Release.Name }}-postgres-credentials"
              key: password
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: "{{.Release.Name}}-app-variables"
              key: POSTGRES_DB
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: "{{.Release.Name}}-app-variables"
              key: DB_HOST