apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{.Release.Name}}-app-variables"
data:
  POSTGRES_USER: '{{ .Values.POSTGRES_USER }}'
  POSTGRES_DB: '{{ .Values.POSTGRES_DB }}'
  DJANGO_ALLOWED_HOSTS: '{{ .Values.DJANGO_ALLOWED_HOSTS }}'
  DATABASES: '{{ .Values.DATABASES }}'
  DB_ENGINE: '{{ .Values.DB_ENGINE }}'
  DB_NAME: '{{ .Values.DB_NAME }}'
  DB_USER: '{{ .Values.DB_USER }}'
  DB_HOST: '{{ .Values.DB_HOST }}'
  DB_PORT: '{{ .Values.DB_PORT }}'