apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{.Release.Name}}-django-deployment"
  labels:
    app: {{.Values.labels.Django}}
spec:
  replicas: {{.Values.deploy.django.replicas}}
  selector:
    matchLabels:
      app: {{.Values.selector.django.app}}
  template:
    metadata:
      labels:
        app: {{.Values.labels.Django}}
    spec:
      containers:
      - name: {{.Values.pod.django.name}}
        image: {{.Values.pod.django.image}}
        command: {{.Values.pod.django.command}}
        ports:
        - containerPort: {{.Values.svc.django.port | int}}
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: "{{ .Release.Name }}-postgres-credentials"
              key: user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: "{{ .Release.Name }}-postgres-credentials"
              key: password
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: "{{.Release.Name}}-app-variables"
              key: POSTGRES_DB
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: "{{.Release.Name}}-app-variables"
              key: DB_HOST