apiVersion: batch/v1
kind: Job
metadata:
  name: "{{.Release.Name}}-django-postgre-migrations"
spec:
  template:
    spec:
      containers:
      - name: {{.Values.job.name}}
        image: {{.Values.job.image}}
        command: {{.Values.job.never}}
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: "{{.Release.Name}}-postgres-credentials"
              key: user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: "{{.Release.Name}}-postgres-credentials"
              key: password
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: "{{.Release.Name}}-app-variables"
              key: POSTGRES_DB
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: "{{.Release.Name}}-app-variables"
              key: DB_HOST
      restartPolicy: {{.Values.job.restartPolicy}}