apiVersion: v1
kind: Service
metadata:
  name: "{{.Release.Name}}-postgres-cluster-ip-service"
spec:
  type: {{.Values.svc.postgres.type}}
  selector:
    app: {{.Values.deploy.postgres.selector.app}}
  ports:
    - protocol: {{.Values.svc.postgres.protocol}}
      port: {{.Values.svc.postgres.port}}
      targetPort: {{.Values.svc.postgres.targetPort}}