name: test

on:
  push:
    branches:
      - "main"
    paths:
      - "Docker/**"

permissions: 
  contents: read 

jobs: 
  build: 
    runs-on: ubuntu-latest  
    steps: 
    - name: Checkout code
      uses: actions/checkout@v3 
    - name: Set up Python 3.8 
      uses: actions/setup-python@v3 
      with: 
        python-version: "3.8" 
    - name: Install dependencies 
      run: | 
        python -m pip install --upgrade pip 
        pip install flake8
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi 
    - name: Lint with flake8 
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics 
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics 
    - name: Run Hadolint
      uses: hadolint/hadolint-action@v3.1.0
      with:
          dockerfile: "*Dockerfile"
    - name: Build an image from Dockerfile
      run: |
        docker build -t rodricamio/crud-django-postgres:${{ github.sha }} .
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'rodricamio/crud-django-postgres:${{ github.sha }}'
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL'
    - name: Build and push to dockerhub
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: rodricamio/crud-django-postgres
        push: true
        tags: latest, ${{ github.run_number }}
        
